(self.AMP=self.AMP||[]).push({n:"amp-mustache",ev:"0.2",l:true,v:"2105210438003",m:0,f:(function(AMP,_){
'use strict';var aa;function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ba(this);"function"===typeof Symbol&&Symbol("x");var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var ha={a:!0},ia={};try{ia.__proto__=ha;ea=ia.a;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var na=da;function ua(a){return a||{}};var va=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function wa(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var v=self.AMP_CONFIG||{},xa=("string"==typeof v.cdnProxyRegex?new RegExp(v.cdnProxyRegex):v.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function Ba(a){if(!self.document||!self.document.head||self.location&&xa.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var Ca={thirdParty:v.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:v.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof v.thirdPartyFrameRegex?new RegExp(v.thirdPartyFrameRegex):v.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:v.cdnUrl||Ba("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:xa,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:v.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:v.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:v.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:v.geoApiUrl||Ba("amp-geo-api")};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var Da=self.__AMP_LOG;function Ea(){if(!Da.user)throw Error("failed to call initLogConstructor");return Da.user}function Fa(a,b,c){Ea().assert(a,b,c,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function Ga(a,b){var c=a=a.__AMP_TOP||(a.__AMP_TOP=a),d=Ha(c),h=d.purifier;h||(h=d.purifier={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null,sharedInstance:!1});h.ctor||(h.ctor=b,h.context=a,h.sharedInstance=!1,h.resolve&&Pa(c,"purifier"))}function Qa(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return Pa(a,b)}function Ra(a){return a.nodeType?Qa((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}
function Pa(a,b){a=Ha(a)[b];a.obj||(a.obj=new a.ctor(a.context),a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Ha(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function Sa(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)};function Ta(a,b){this.element=a;this.win=a.ownerDocument.defaultView||b;a=Ra(this.element);a=Ra(a);a=a.isSingleDoc()?a.win:a;this.L=Pa(a,"viewer");this.compileCallback()}aa=Ta.prototype;aa.compileCallback=function(){};aa.setHtml=function(){};aa.render=function(){};aa.renderAsString=function(){};function Ua(a,b){for(a=a.firstChild;null!=a;a=a.nextSibling)if(3==a.nodeType){var c=a.textContent.trim();c&&b(c)}else 8!=a.nodeType&&1==(null==a?void 0:a.nodeType)&&b(a)}
aa.tryUnwrap=function(a){var b;Ua(a,function(c){b=void 0===b&&c.nodeType?c:null});return b||a};aa.unwrapChildren=function(a){var b=this,c=[];Ua(a,function(d){if("string"==typeof d){var h=b.win.document.createElement("div");h.textContent=d;c.push(h)}else c.push(d)});return c};aa.viewerCanRenderTemplates=function(){return this.L.hasCapability("viewerRenderTemplate")};function Va(a){var b=a.documentElement;return["\u26a14email","amp4email"].some(function(c){return b.hasAttribute(c)})};function Wa(){this.J=100;this.B=this.D=0;this.o=Object.create(null)}Wa.prototype.has=function(a){return!!this.o[a]};Wa.prototype.get=function(a){var b=this.o[a];if(b)return b.access=++this.B,b.payload};Wa.prototype.put=function(a,b){this.has(a)||this.D++;this.o[a]={payload:b,access:this.B};if(!(this.D<=this.J)){a=this.o;var c=this.B+1,d;for(d in a){var h=a[d].access;if(h<c){c=h;var r=d}}void 0!==r&&(delete a[r],this.D--)}};var Xa=ua({c:!0,v:!0,a:!0,ad:!0}),Ya,Za,$a=/[?&]amp_js[^&]*/,ab=/[?&]amp_gsa[^&]*/,bb=/[?&]amp_r[^&]*/,cb=/[?&]amp_kit[^&]*/,lb=/[?&]usqp[^&]*/;
function mb(a){Ya||(Ya=self.document.createElement("a"),Za=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new Wa));var b=Za,c=Ya;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a}function nb(a){"string"==typeof a&&(a=mb(a));return Ca.cdnProxyRegex.test(a.origin)}
function ob(a){"string"==typeof a&&(a=mb(a));if(!nb(a))return a.href;var b=a.pathname.split("/");Fa(Xa[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);Fa(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");d=(d=a.search)&&"?"!=d?(d=d.replace($a,"").replace(ab,"").replace(bb,"").replace(cb,"").replace(lb,"").replace(/^[?&]/,""))?"?"+d:"":"";return b+d+(a.hash||"")}
function pb(a,b){"string"==typeof b&&(b=mb(b));if("function"==typeof URL)var c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=mb(d));c=c.replace(/\\/g,"/");var h=mb(c);c=c.toLowerCase().startsWith(h.protocol)?h.href:c.startsWith("//")?d.protocol+c:c.startsWith("/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c}
function qb(a){var b=mb(a).search,c=Object.create(null);if(b)for(var d;d=va.exec(b);){var h=wa(d[1],d[1]);d=d[2]?wa(d[2].replace(/\+/g," "),d[2]):"";c[h]=d}Fa(!("__amp_source_origin"in c),"Source origin is not allowed in %s",a)};var rb=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function sb(a){for(var b=[],c;c=rb.exec(a);){var d=c[1],h=void 0,r=void 0;if(c[2]){var y=c[3].toLowerCase();if("w"==y)h=parseInt(c[2],10);else if("x"==y)r=parseFloat(c[2]);else continue}else r=1;b.push({url:d,width:h,dpr:r})}return new tb(b)}
function tb(a){Fa(0<a.length,"Srcset must have at least one source");this.j=a;for(var b=!1,c=!1,d=0;d<a.length;d++){var h=a[d];b=b||!!h.width;c=c||!!h.dpr}Fa(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?ub:vb);this.I=b}
tb.prototype.select=function(a,b){if(this.I){b*=a;a=this.j;for(var c=0,d=Infinity,h=Infinity,r=0;r<a.length;r++){var y=a[r].width,u=Math.abs(y-b);if(u<=1.1*d||1.2<b/h)c=r,d=u,h=y;else break}b=c}else{a=this.j;c=0;d=Infinity;for(h=0;h<a.length;h++)if(r=Math.abs(a[h].dpr-b),r<=d)c=h,d=r;else break;b=c}return this.j[b].url};tb.prototype.getUrls=function(){return this.j.map(function(a){return a.url})};
tb.prototype.stringify=function(a){for(var b=[],c=this.j,d=0;d<c.length;d++){var h=c[d],r=h.url;a&&(r=a(r));r=this.I?r+(" "+h.width+"w"):r+(" "+h.dpr+"x");b.push(r)}return b.join(", ")};function ub(a,b){Fa(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function vb(a,b){Fa(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};function wb(a,b,c){return xb(b)?yb(a,b,c):c}function xb(a){return"src"==a||"href"==a||"xlink:href"==a||"srcset"==a}function yb(a,b,c){var d=self.location;qb(c);var h=nb(d),r=mb(ob(d));if("href"==b&&!c.startsWith("#"))return pb(c,r);if("src"==b)return"amp-img"==a?zb(c,r,h):pb(c,r);if("srcset"==b){try{var y=sb(c)}catch(u){return Ea().error("URL-REWRITE","Failed to parse srcset: ",u),c}return y.stringify(function(u){return zb(u,r,h)})}return c}
function zb(a,b,c){a=mb(pb(a,b));return"data:"==a.protocol||nb(a)||!c?a.href:Ca.cdn+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};var Ab={"AMP-IMG":["src","srcset","layout","width","height"]};function Bb(a,b){var c=a.tagName.startsWith("AMP-"),d=a.hasAttribute("i-amphtml-binding");if(!d&&Ab[a.tagName])a.setAttribute("i-amphtml-ignore","");else if(d||c)a.hasAttribute("i-amphtml-key")||a.setAttribute("i-amphtml-key",b())}
var Cb={applet:!0,audio:!0,base:!0,embed:!0,frame:!0,frameset:!0,iframe:!0,img:!0,link:!0,meta:!0,object:!0,style:!0,video:!0},Db={"amp-accordion":!0,"amp-anim":!0,"amp-bind-macro":!0,"amp-carousel":!0,"amp-fit-text":!0,"amp-img":!0,"amp-layout":!0,"amp-selector":!0,"amp-sidebar":!0,"amp-timeago":!0},Eb="a amp-img article aside b blockquote br caption code col colgroup dd del details div dl dt em figcaption figure footer h1 h2 h3 header hr i ins li main mark nav ol p pre q s section small span strong sub summary sup table tbody td tfoot th thead time tr u ul".split(" "),
Fb="amp-fx fallback heights layout min-font-size max-font-size on option placeholder submitting submit-success submit-error validation-for verify-error visible-when-invalid href style text subscriptions-action subscriptions-actions subscriptions-decorate subscriptions-dialog subscriptions-display subscriptions-section subscriptions-service subscriptions-google-rtc amp-nested-submenu amp-nested-submenu-open amp-nested-submenu-close itemprop".split(" "),Gb={a:["rel","target"],div:["template"],form:["action-xhr",
"verify-xhr","custom-validation-reporting","target"],input:["mask-output"],template:["type"],textarea:["autoexpand"]},Hb=["_top","_blank"],Ib=/^(?:\w+script|data|blob):/i,Jb=/^(?:blob):/i,Kb=/[\u0000-\u0020\u00A0\u1680\u180E\u2000-\u2029\u205f\u3000]/g,Lb=Object.freeze(ua({input:{type:/(?:image|button)/i}})),Mb=Object.freeze(ua({input:{type:/(?:button|file|image|password)/i}})),Nb=Object.freeze("form formaction formmethod formtarget formnovalidate formenctype".split(" ")),Ob=Object.freeze(ua({input:Nb,
textarea:Nb,select:Nb})),Pb=Object.freeze(ua({"amp-anim":["controls"],form:["name"]})),Qb=/!important|position\s*:\s*fixed|position\s*:\s*sticky/i;
function bc(a,b,c,d){var h=!0,r=h=void 0===h?!1:h,y=c?c.replace(Kb,""):"";if(!r){if(b.startsWith("on")&&"on"!=b)return!1;var u=y.toLowerCase();if(0<=u.indexOf("<script")||0<=u.indexOf("\x3c/script")||Ib.test(y))return!1}if(Jb.test(y))return!1;if("style"==b)return!Qb.test(c);if("class"==b&&c&&/(^|\W)i-amphtml-/i.test(c)||xb(b)&&/__amp_source_origin/.test(c))return!1;var C=Va(d),D=Object.assign(Object.create(null),Ob,C?Pb:{})[a];if(D&&-1!=D.indexOf(b))return!1;var E=Object.assign(Object.create(null),
Lb,C?Mb:{})[a];if(E){var A=E[b];if(A&&-1!=c.search(A))return!1}return!0};/*
 @license DOMPurify | (c) Cure53 and other contributors | Released under the Apache license 2.0 and Mozilla Public License 2.0 | github.com/cure53/DOMPurify/blob/2.2.2/LICENSE */
var cc=Object.hasOwnProperty,dc=Object.setPrototypeOf,ec=Object.isFrozen,fc=Object.getPrototypeOf,gc=Object.getOwnPropertyDescriptor,K=Object.freeze,N=Object.seal,hc=Object.create,ic="undefined"!==typeof Reflect&&Reflect,jc=ic.apply,kc=ic.construct;jc||(jc=function(a,b,c){return a.apply(b,c)});K||(K=function(a){return a});N||(N=function(a){return a});
kc||(kc=function(a,b){var c=Function.prototype.bind,d=c.apply,h=[null],r=h.concat;if(Array.isArray(b)){for(var y=0,u=Array(b.length);y<b.length;y++)u[y]=b[y];b=u}else b=Array.from(b);return new (d.call(c,a,r.call(h,b)))});var lc=T(Array.prototype.forEach),mc=T(Array.prototype.pop),nc=T(Array.prototype.push),oc=T(String.prototype.toLowerCase),pc=T(String.prototype.match),qc=T(String.prototype.replace),rc=T(String.prototype.indexOf),sc=T(String.prototype.trim),tc=T(RegExp.prototype.test),vc=uc();
function T(a){return function(b){for(var c=arguments.length,d=Array(1<c?c-1:0),h=1;h<c;h++)d[h-1]=arguments[h];return jc(a,b,d)}}function uc(){var a=TypeError;return function(){for(var b=arguments.length,c=Array(b),d=0;d<b;d++)c[d]=arguments[d];return kc(a,c)}}function U(a,b){dc&&dc(a,null);for(var c=b.length;c--;){var d=b[c];if("string"===typeof d){var h=oc(d);h!==d&&(ec(b)||(b[c]=h),d=h)}a[d]=!0}return a}function wc(a){var b=hc(null),c=void 0;for(c in a)jc(cc,a,[c])&&(b[c]=a[c]);return b}
function xc(a,b){for(;null!==a;){var c=gc(a,b);if(c){if(c.get)return T(c.get);if("function"===typeof c.value)return T(c.value)}a=fc(a)}return function(d){console.warn("fallback value for",d);return null}}
var yc=K("a abbr acronym address area article aside audio b bdi bdo big blink blockquote body br button canvas caption center cite code col colgroup content data datalist dd decorator del details dfn dialog dir div dl dt element em fieldset figcaption figure font footer form h1 h2 h3 h4 h5 h6 head header hgroup hr html i img input ins kbd label legend li main map mark marquee menu menuitem meter nav nobr ol optgroup option output p picture pre progress q rp rt ruby s samp section select shadow small source spacer span strike strong style sub summary sup table tbody td template textarea tfoot th thead time tr track tt u ul var video wbr".split(" ")),zc=
K("svg a altglyph altglyphdef altglyphitem animatecolor animatemotion animatetransform circle clippath defs desc ellipse filter font g glyph glyphref hkern image line lineargradient marker mask metadata mpath path pattern polygon polyline radialgradient rect stop style switch symbol text textpath title tref tspan view vkern".split(" ")),Ac=K("feBlend feColorMatrix feComponentTransfer feComposite feConvolveMatrix feDiffuseLighting feDisplacementMap feDistantLight feFlood feFuncA feFuncB feFuncG feFuncR feGaussianBlur feMerge feMergeNode feMorphology feOffset fePointLight feSpecularLighting feSpotLight feTile feTurbulence".split(" ")),
Bc=K("animate color-profile cursor discard fedropshadow feimage font-face font-face-format font-face-name font-face-src font-face-uri foreignobject hatch hatchpath mesh meshgradient meshpatch meshrow missing-glyph script set solidcolor unknown use".split(" ")),Cc=K("math menclose merror mfenced mfrac mglyph mi mlabeledtr mmultiscripts mn mo mover mpadded mphantom mroot mrow ms mspace msqrt mstyle msub msup msubsup mtable mtd mtext mtr munder munderover".split(" ")),Dc=K("maction maligngroup malignmark mlongdiv mscarries mscarry msgroup mstack msline msrow semantics annotation annotation-xml mprescripts none".split(" ")),
Ec=K(["#text"]),Fc=K("accept action align alt autocapitalize autocomplete autopictureinpicture autoplay background bgcolor border capture cellpadding cellspacing checked cite class clear color cols colspan controls controlslist coords crossorigin datetime decoding default dir disabled disablepictureinpicture disableremoteplayback download draggable enctype enterkeyhint face for headers height hidden high href hreflang id inputmode integrity ismap kind label lang list loading loop low max maxlength media method min minlength multiple muted name noshade novalidate nowrap open optimum pattern placeholder playsinline poster preload pubdate radiogroup readonly rel required rev reversed role rows rowspan spellcheck scope selected shape size sizes span srclang start src srcset step style summary tabindex title translate type usemap valign value width xmlns slot".split(" ")),
Gc=K("accent-height accumulate additive alignment-baseline ascent attributename attributetype azimuth basefrequency baseline-shift begin bias by class clip clippathunits clip-path clip-rule color color-interpolation color-interpolation-filters color-profile color-rendering cx cy d dx dy diffuseconstant direction display divisor dur edgemode elevation end fill fill-opacity fill-rule filter filterunits flood-color flood-opacity font-family font-size font-size-adjust font-stretch font-style font-variant font-weight fx fy g1 g2 glyph-name glyphref gradientunits gradienttransform height href id image-rendering in in2 k k1 k2 k3 k4 kerning keypoints keysplines keytimes lang lengthadjust letter-spacing kernelmatrix kernelunitlength lighting-color local marker-end marker-mid marker-start markerheight markerunits markerwidth maskcontentunits maskunits max mask media method mode min name numoctaves offset operator opacity order orient orientation origin overflow paint-order path pathlength patterncontentunits patterntransform patternunits points preservealpha preserveaspectratio primitiveunits r rx ry radius refx refy repeatcount repeatdur restart result rotate scale seed shape-rendering specularconstant specularexponent spreadmethod startoffset stddeviation stitchtiles stop-color stop-opacity stroke-dasharray stroke-dashoffset stroke-linecap stroke-linejoin stroke-miterlimit stroke-opacity stroke stroke-width style surfacescale systemlanguage tabindex targetx targety transform text-anchor text-decoration text-rendering textlength type u1 u2 unicode values viewbox visibility version vert-adv-y vert-origin-x vert-origin-y width word-spacing wrap writing-mode xchannelselector ychannelselector x x1 x2 xmlns y y1 y2 z zoomandpan".split(" ")),
Hc=K("accent accentunder align bevelled close columnsalign columnlines columnspan denomalign depth dir display displaystyle encoding fence frame height href id largeop length linethickness lspace lquote mathbackground mathcolor mathsize mathvariant maxsize minsize movablelimits notation numalign open rowalign rowlines rowspacing rowspan rspace rquote scriptlevel scriptminsize scriptsizemultiplier selection separator separators stretchy subscriptshift supscriptshift symmetric voffset width xmlns".split(" ")),
Ic=K(["xlink:href","xml:id","xlink:title","xml:space","xmlns:xlink"]),Jc=N(/\{\{[\s\S]*|[\s\S]*\}\}/gm),Kc=N(/<%[\s\S]*|[\s\S]*%>/gm),Lc=N(/^data-[\-\w.\u00B7-\uFFFF]/),Mc=N(/^aria-[\-\w]+$/),Nc=N(/^(?:(?:(?:f|ht)tps?|mailto|tel|callto|cid|xmpp):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i),Oc=N(/^(?:\w+script|data):/i),Pc=N(/[\u0000-\u0020\u00A0\u1680\u180E\u2000-\u2029\u205F\u3000]/g),Qc="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===
typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};function W(a){if(Array.isArray(a)){for(var b=0,c=Array(a.length);b<a.length;b++)c[b]=a[b];return c}return Array.from(a)}
function Rc(a,b){if("object"!==("undefined"===typeof a?"undefined":Qc(a))||"function"!==typeof a.createPolicy)return null;var c=null;b.currentScript&&b.currentScript.hasAttribute("data-tt-policy-suffix")&&(c=b.currentScript.getAttribute("data-tt-policy-suffix"));var d="dompurify"+(c?"#"+c:"");try{return a.createPolicy(d,{createHTML:function(h){return h}})}catch(h){return console.warn("TrustedTypes policy "+d+" could not be created."),null}}
function Sc(){function a(e){var g,m;d("beforeSanitizeAttributes",e,null);var n=e.attributes;if(n){var F={attrName:"",attrValue:"",keepAttr:!0,allowedAttributes:J};for(m=n.length;m--;){var ja=g=n[m],R=ja.name,Ia=ja.namespaceURI;g=sc(g.value);var Z=oc(R);F.attrName=Z;F.attrValue=g;F.keepAttr=!0;F.forceKeepAttr=void 0;d("uponSanitizeAttribute",e,F);g=F.attrValue;if(!F.forceKeepAttr&&(C(R,e),F.keepAttr))if(tc(/\/>/i,g))C(R,e);else{oa&&(g=qc(g,Jc," "),g=qc(g,Kc," "));var cd=e.nodeName.toLowerCase();if(b(cd,
Z,g))try{Ia?e.setAttributeNS(Ia,R,g):e.setAttribute(R,g),mc(q.removed)}catch(ld){}}}d("afterSanitizeAttributes",e,null)}}function b(e,g,m){if(Rb&&("id"===g||"name"===g)&&(m in O||m in dd))return!1;if(!db||!tc(Lc,g))if(!Sb||!tc(Mc,g))if(!J[g]||Tb[g]||!(eb[g]||tc(X,qc(m,Pc,""))||("src"===g||"xlink:href"===g||"href"===g)&&"script"!==e&&0===rc(m,"data:")&&Ub[e]||Vb&&!tc(Oc,qc(m,Pc,"")))&&m)return!1;return!0}function c(e){d("beforeSanitizeElements",e,null);if(r(e))return D(e),!0;if(pc(e.nodeName,/[\u0080-\uFFFF]/))return D(e),
!0;var g=oc(e.nodeName);d("uponSanitizeElement",e,{tagName:g,allowedTags:H});if(!(h(e.firstElementChild)||h(e.content)&&h(e.content.firstElementChild))&&tc(/<[/\w]/g,e.innerHTML)&&tc(/<[/\w]/g,e.textContent))return D(e),!0;if(!H[g]||fb[g]){if(gb&&!ed[g]){var m=x(e)||e.parentNode,n=z(e)||e.childNodes;if(n&&m)for(g=n.length-1;0<=g;--g)m.insertBefore(p(n[g],!0),w(e))}D(e);return!0}if(e instanceof Ja&&!E(e)||("noscript"===g||"noembed"===g)&&tc(/<\/no(script|embed)/i,e.innerHTML))return D(e),!0;oa&&3===
e.nodeType&&(g=e.textContent,g=qc(g,Jc," "),g=qc(g,Kc," "),e.textContent!==g&&(nc(q.removed,{element:e.cloneNode()}),e.textContent=g));d("afterSanitizeElements",e,null);return!1}function d(e,g,m){L[e]&&lc(L[e],function(n){n.call(q,g,m,pa)})}function h(e){return"object"===("undefined"===typeof qa?"undefined":Qc(qa))?e instanceof qa:e&&"object"===("undefined"===typeof e?"undefined":Qc(e))&&"number"===typeof e.nodeType&&"string"===typeof e.nodeName}function r(e){return e instanceof ya||e instanceof f?
!1:"string"===typeof e.nodeName&&"string"===typeof e.textContent&&"function"===typeof e.removeChild&&e.attributes instanceof hb&&"function"===typeof e.removeAttribute&&"function"===typeof e.setAttribute&&"string"===typeof e.namespaceURI&&"function"===typeof e.insertBefore?!1:!0}function y(e){return G.call(e.ownerDocument||e,e,ka.SHOW_ELEMENT|ka.SHOW_COMMENT|ka.SHOW_TEXT,function(){return ka.FILTER_ACCEPT},!1)}function u(e){var g=void 0,m=void 0;if(ib)e="<remove></remove>"+e;else{var n=pc(e,/^[\r\n\t ]+/);
m=n&&n[0]}var F=t?t.createHTML(e):e;if("http://www.w3.org/1999/xhtml"===Ka)try{g=(new k).parseFromString(F,"text/html")}catch(ja){}g&&g.documentElement||(g=fa.createDocument(Ka,"template",null),g.documentElement.innerHTML=F);n=g.body||g.documentElement;e&&m&&n.insertBefore(O.createTextNode(m),n.childNodes[0]||null);return za?g.documentElement:n}function C(e,g){try{nc(q.removed,{attribute:g.getAttributeNode(e),from:g})}catch(m){nc(q.removed,{attribute:null,from:g})}g.removeAttribute(e);if("is"===e&&
!J[e])if(ra||La)try{D(g)}catch(m){}else try{g.setAttribute(e,"")}catch(m){}}function D(e){nc(q.removed,{element:e});try{e.parentNode.removeChild(e)}catch(g){try{e.outerHTML=M}catch(m){e.remove()}}}function E(e){var g=x(e);g&&g.tagName||(g={namespaceURI:"http://www.w3.org/1999/xhtml",tagName:"template"});var m=oc(e.tagName),n=oc(g.tagName);if("http://www.w3.org/2000/svg"===e.namespaceURI)return"http://www.w3.org/1999/xhtml"===g.namespaceURI?"svg"===m:"http://www.w3.org/1998/Math/MathML"===g.namespaceURI?
"svg"===m&&("annotation-xml"===n||Wb[n]):!!Ma[m];if("http://www.w3.org/1998/Math/MathML"===e.namespaceURI)return"http://www.w3.org/1999/xhtml"===g.namespaceURI?"math"===m:"http://www.w3.org/2000/svg"===g.namespaceURI?"math"===m&&Xb[n]:!!jb[m];if("http://www.w3.org/1999/xhtml"===e.namespaceURI){if("http://www.w3.org/2000/svg"===g.namespaceURI&&!Xb[n]||"http://www.w3.org/1998/Math/MathML"===g.namespaceURI&&!Wb[n])return!1;var F=U({},["title","style","font","a","script"]);return!jb[m]&&(F[m]||!Ma[m])}return!1}
function A(e){pa&&pa===e||(e&&"object"===("undefined"===typeof e?"undefined":Qc(e))||(e={}),e=wc(e),H="ALLOWED_TAGS"in e?U({},e.ALLOWED_TAGS):S,J="ALLOWED_ATTR"in e?U({},e.ALLOWED_ATTR):Yb,eb="ADD_URI_SAFE_ATTR"in e?U(wc(Zb),e.ADD_URI_SAFE_ATTR):Zb,Ub="ADD_DATA_URI_TAGS"in e?U(wc($b),e.ADD_DATA_URI_TAGS):$b,fb="FORBID_TAGS"in e?U({},e.FORBID_TAGS):{},Tb="FORBID_ATTR"in e?U({},e.FORBID_ATTR):{},sa="USE_PROFILES"in e?e.USE_PROFILES:!1,Sb=!1!==e.ALLOW_ARIA_ATTR,db=!1!==e.ALLOW_DATA_ATTR,Vb=e.ALLOW_UNKNOWN_PROTOCOLS||
!1,oa=e.SAFE_FOR_TEMPLATES||!1,za=e.WHOLE_DOCUMENT||!1,ra=e.RETURN_DOM||!1,La=e.RETURN_DOM_FRAGMENT||!1,ac=!1!==e.RETURN_DOM_IMPORT,Na=e.RETURN_TRUSTED_TYPE||!1,ib=e.FORCE_BODY||!1,Rb=!1!==e.SANITIZE_DOM,gb=!1!==e.KEEP_CONTENT,Aa=e.IN_PLACE||!1,X=e.ALLOWED_URI_REGEXP||X,Ka=e.NAMESPACE||Ka,oa&&(db=!1),La&&(ra=!0),sa&&(H=U({},[].concat(W(Ec))),J=[],!0===sa.html&&(U(H,yc),U(J,Fc)),!0===sa.svg&&(U(H,zc),U(J,Gc),U(J,Ic)),!0===sa.svgFilters&&(U(H,Ac),U(J,Gc),U(J,Ic)),!0===sa.mathMl&&(U(H,Cc),U(J,Hc),U(J,
Ic))),e.ADD_TAGS&&(H===S&&(H=wc(H)),U(H,e.ADD_TAGS)),e.ADD_ATTR&&(J===Yb&&(J=wc(J)),U(J,e.ADD_ATTR)),e.ADD_URI_SAFE_ATTR&&U(eb,e.ADD_URI_SAFE_ATTR),gb&&(H["#text"]=!0),za&&U(H,["html","head","body"]),H.table&&(U(H,["tbody"]),delete fb.tbody),K&&K(e),pa=e)}function q(e){return Sc(e)}var B=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"undefined"===typeof window?null:window;q.version="2.2.8";q.removed=[];if(!B||!B.document||9!==B.document.nodeType)return q.isSupported=!1,q;var P=B.document,
O=B.document,Oa=B.DocumentFragment,la=B.HTMLTemplateElement,qa=B.Node,Ja=B.Element,ka=B.NodeFilter,ta=B.NamedNodeMap,hb=void 0===ta?B.NamedNodeMap||B.MozNamedAttrMap:ta,ya=B.Text,f=B.Comment,k=B.DOMParser;ta=B.trustedTypes;var l=Ja.prototype,p=xc(l,"cloneNode"),w=xc(l,"nextSibling"),z=xc(l,"childNodes"),x=xc(l,"parentNode");"function"===typeof la&&(la=O.createElement("template"),la.content&&la.content.ownerDocument&&(O=la.content.ownerDocument));var t=Rc(ta,P),M=t&&Na?t.createHTML(""):"",Q=O,fa=Q.implementation,
G=Q.createNodeIterator,I=Q.createDocumentFragment,V=P.importNode,ma={};try{ma=wc(O).documentMode?O.documentMode:{}}catch(e){}var L={};q.isSupported="function"===typeof x&&fa&&"undefined"!==typeof fa.createHTMLDocument&&9!==ma;var X=Nc,H=null,S=U({},[].concat(W(yc),W(zc),W(Ac),W(Cc),W(Ec))),J=null,Yb=U({},[].concat(W(Fc),W(Gc),W(Hc),W(Ic))),fb=null,Tb=null,Sb=!0,db=!0,Vb=!1,oa=!1,za=!1,kb=!1,ib=!1,ra=!1,La=!1,ac=!0,Na=!1,Rb=!0,gb=!0,Aa=!1,sa={},ed=U({},"annotation-xml audio colgroup desc foreignobject head iframe math mi mn mo ms mtext noembed noframes noscript plaintext script style svg template thead title video xmp".split(" ")),
Ub=null,$b=U({},"audio video img source image track".split(" ")),eb=null,Zb=U({},"alt class for id label name pattern placeholder summary title value style xmlns".split(" ")),Ka="http://www.w3.org/1999/xhtml",pa=null,dd=O.createElement("form"),Wb=U({},["mi","mo","mn","ms","mtext"]),Xb=U({},["foreignobject","desc","title","annotation-xml"]),Ma=U({},zc);U(Ma,Ac);U(Ma,Bc);var jb=U({},Cc);U(jb,Dc);var fd=function m(g){var n=void 0,F=y(g);for(d("beforeSanitizeShadowDOM",g,null);n=F.nextNode();)d("uponSanitizeShadowNode",
n,null),c(n)||(n.content instanceof Oa&&m(n.content),a(n));d("afterSanitizeShadowDOM",g,null)};q.sanitize=function(g,m){var n=void 0,F=void 0,ja=void 0,R=void 0;g||(g="\x3c!--\x3e");if("string"!==typeof g&&!h(g)){if("function"!==typeof g.toString)throw vc("toString is not a function");g=g.toString();if("string"!==typeof g)throw vc("dirty is not a string, aborting");}if(!q.isSupported){if("object"===Qc(B.toStaticHTML)||"function"===typeof B.toStaticHTML){if("string"===typeof g)return B.toStaticHTML(g);
if(h(g))return B.toStaticHTML(g.outerHTML)}return g}kb||A(m);q.removed=[];"string"===typeof g&&(Aa=!1);if(!Aa)if(g instanceof qa)n=u("\x3c!----\x3e"),F=n.ownerDocument.importNode(g,!0),1===F.nodeType&&"BODY"===F.nodeName?n=F:"HTML"===F.nodeName?n=F:n.appendChild(F);else{if(!ra&&!oa&&!za&&-1===g.indexOf("<"))return t&&Na?t.createHTML(g):g;n=u(g);if(!n)return ra?null:M}n&&ib&&D(n.firstChild);for(var Ia=y(Aa?g:n);m=Ia.nextNode();)3===m.nodeType&&m===ja||c(m)||(m.content instanceof Oa&&fd(m.content),
a(m),ja=m);ja=null;if(Aa)return g;if(ra){if(La)for(R=I.call(n.ownerDocument);n.firstChild;)R.appendChild(n.firstChild);else R=n;ac&&(R=V.call(P,R,!0));return R}var Z=za?n.outerHTML:n.innerHTML;oa&&(Z=qc(Z,Jc," "),Z=qc(Z,Kc," "));return t&&Na?t.createHTML(Z):Z};q.setConfig=function(g){A(g);kb=!0};q.clearConfig=function(){pa=null;kb=!1};q.isValidAttribute=function(g,m,n){pa||A({});g=oc(g);m=oc(m);return b(g,m,n)};q.addHook=function(g,m){"function"===typeof m&&(L[g]=L[g]||[],nc(L[g],m))};q.removeHook=
function(g){L[g]&&mc(L[g])};q.removeHooks=function(g){L[g]&&(L[g]=[])};q.removeAllHooks=function(){L={}};return q}var Tc=Sc();var Uc={script:{attribute:"type",values:["application/json","application/ld+json"]}},Vc={USE_PROFILES:{html:!0,svg:!0,svgFilters:!0}};function Wc(a){this.A=a;this.K=1;this.h=Tc(self);this.F=Tc(self);a=Object.assign({},Object.assign({},Vc,{ADD_ATTR:Fb,ADD_TAGS:["use"],FORBID_TAGS:Object.keys(Cb),FORCE_BODY:!0,RETURN_DOM:!0,ALLOW_UNKNOWN_PROTOCOLS:!0}));this.h.setConfig(a);Xc(this,this.h);Yc(this.F)}Wc.prototype.purifyHtml=function(a){return this.h.sanitize(a)};
Wc.prototype.purifyTagsForTripleMustache=function(a){a=this.F.sanitize(a,{ALLOWED_TAGS:Eb,FORCE_BODY:!0,RETURN_DOM_FRAGMENT:!0});var b=this.A.createElement("div");b.appendChild(a);return b.innerHTML};Wc.prototype.getAllowedTags=function(){var a={};this.h.addHook("uponSanitizeElement",function(c,d){Object.assign(a,d.allowedTags)});var b=this.A.createElement("p");this.h.sanitize(b);Object.keys(Cb).forEach(function(c){a[c]=!1});this.h.removeHook("uponSanitizeElement");return a};
Wc.prototype.validateAttributeChange=function(a,b,c){var d=a.nodeName.toLowerCase(),h=Uc[d];if(h){var r=h.values;if(h.attribute===b&&(null==c||!r.includes(c)))return!1}if("a"===d&&"target"===b&&(null==c||!Hb.includes(c)))return!1;if(null==c)return!0;if(Zc(b)!==$c)return!1;if(!this.h.isValidAttribute(d,b,c)){var y=Gb[d];if(!(y&&y.includes(b)||d.startsWith("amp-")))return!1}a=a.ownerDocument?a.ownerDocument:a;return c&&!bc(d,b,c,a)?!1:!0};
function Xc(a,b){var c=Va(a.A),d,h=[],r,y=[];b.addHook("uponSanitizeElement",function(u,C){var D=C.tagName;d=C.allowedTags;D.startsWith("amp-")&&(d[D]=!c||Db[D]);"a"===D&&u.hasAttribute("href")&&!u.hasAttribute("target")&&u.setAttribute("target","_top");var E=Uc[D];E&&(C=E.attribute,E=E.values,u.hasAttribute(C)&&E.includes(u.getAttribute(C))&&(d[D]=!0,h.push(D)))});b.addHook("afterSanitizeElements",function(){h.forEach(function(u){delete d[u]});h.length=0});b.addHook("uponSanitizeAttribute",function(u,
C){function D(){r[A]||(r[A]=!0,y.push(A))}var E=u.nodeName.toLowerCase(),A=C.attrName,q=C.attrValue;r=C.allowedAttributes;if(E.startsWith("amp-"))D();else{if("a"==E&&"target"==A){var B=q.toLowerCase();q=Hb.includes(B)?B:"_top"}var P=Gb[E];P&&P.includes(A)&&D()}var O=Zc(A);O===ad&&(P=A.substring(1,A.length-1),u.setAttribute("data-amp-bind-"+P,q));O!==$c&&u.setAttribute("i-amphtml-binding","");bc(E,A,q,a.A)?wb&&q&&!A.startsWith("data-amp-bind-")&&(q=wb(E,A,q)):(C.keepAttr=!1,Ea().error("purifier",'Removed invalid attribute %s[%s="%s"].',
E,A,q));C.attrValue=q});b.addHook("afterSanitizeAttributes",function(u){Bb(u,function(){return String(a.K++)});y.forEach(function(C){delete r[C]});y.length=0;"use"===u.nodeName.toLowerCase()&&["href","xlink:href"].forEach(function(C){u.hasAttribute(C)&&!u.getAttribute(C).startsWith("#")&&(u.parentElement&&u.parentElement.removeChild(u),Ea().error("purifier",'Removed invalid <use>. use[href] must start with "#".'))})})}
function Yc(a){var b;a.addHook("uponSanitizeElement",function(c,d){var h=d.tagName;b=d.allowedTags;"template"===h&&(c=c.getAttribute("type"))&&"amp-mustache"===c.toLowerCase()&&(b.template=!0)});a.addHook("afterSanitizeElements",function(){b.template=!1})}var $c=0,ad=1,bd=2;function Zc(a){return"["==a[0]&&"]"==a[a.length-1]?ad:a.startsWith("data-amp-bind-")?bd:$c};/*
 mustache.js - Logic-less {{mustache}} templates with JavaScript
 http://github.com/janl/mustache.js
*/
var gd={};
(function(a){function b(f){return"function"===typeof f}function c(f){return P(f)?"array":typeof f}function d(f){return f.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&")}function h(f,k){return null!=f&&"object"===typeof f&&Object.prototype.hasOwnProperty.call(f,k)}function r(f,k){return O.call(f,k)}function y(f){return!r(Oa,f)}function u(f,k){function l(){if(x&&!t)for(;z.length;)delete w[z.pop()];else z=[];t=x=!1}if(!f)return[];var p=[],w=[],z=[],x=!1,t=!1,M,Q,fa;(function(S){"string"===typeof S&&(S=
S.split(Ja,2));if(!P(S)||2!==S.length)throw Error("Invalid tags: "+S);M=new RegExp(d(S[0])+"\\s*");Q=new RegExp("\\s*"+d(S[1]));fa=new RegExp("\\s*"+d("}"+S[1]))})(k||a.tags);for(var G=new E(f),I,V,ma,L,X;!G.eos();){f=G.pos;if(V=G.scanUntil(M)){I=0;for(var H=V.length;I<H;++I)ma=V.charAt(I),y(ma)?z.push(w.length):t=!0,w.push(["text",ma,f,f+1]),f+=1,"\n"===ma&&l()}if(!G.scan(M))break;x=!0;I=G.scan(hb)||"name";G.scan(qa);"="===I?(V=G.scanUntil(ka),G.scan(ka),G.scanUntil(Q)):"{"===I?(V=G.scanUntil(fa),
G.scan(ta),G.scanUntil(Q),I="&"):V=G.scanUntil(Q);if(!G.scan(Q))throw Error("Unclosed tag at "+G.pos);L=[I,V,f,G.pos];w.push(L);if("#"===I||"^"===I)p.push(L);else if("/"===I){X=p.pop();if(!X)throw Error('Unopened section "'+V+'" at '+f);if(X[1]!==V)throw Error('Unclosed section "'+X[1]+'" at '+f);}else if("name"===I||"{"===I||"&"===I)t=!0}if(X=p.pop())throw Error('Unclosed section "'+X[1]+'" at '+G.pos);return D(C(w))}function C(f){for(var k=[],l,p,w=0,z=f.length;w<z;++w)if(l=f[w])"text"===l[0]&&
p&&"text"===p[0]?(p[1]+=l[1],p[3]=l[3]):(k.push(l),p=l);return k}function D(f){for(var k=[],l=k,p=[],w,z,x=0,t=f.length;x<t;++x)switch(w=f[x],w[0]){case "#":case "^":l.push(w);p.push(w);l=w[4]=[];break;case "/":z=p.pop();z[5]=w[2];l=0<p.length?p[p.length-1][4]:k;break;default:l.push(w)}return k}function E(f){this.tail=this.string=f;this.pos=0}function A(f,k){this.view=f;this.cache={".":this.view};this.parent=k}function q(){this.cache={}}var B=Object.prototype.toString,P=Array.isArray||function(f){return"[object Array]"===
B.call(f)},O=RegExp.prototype.test,Oa=/\S/,la={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;","`":"&#x60;","=":"&#x3D;"},qa=/\s*/,Ja=/\s+/,ka=/\s*=/,ta=/\s*\}/,hb=/#|\^|\/|>|\{|&|=|!/;E.prototype.eos=function(){return""===this.tail};E.prototype.scan=function(f){f=this.tail.match(f);if(!f||0!==f.index)return"";f=f[0];this.tail=this.tail.substring(f.length);this.pos+=f.length;return f};E.prototype.scanUntil=function(f){f=this.tail.search(f);switch(f){case -1:var k=this.tail;
this.tail="";break;case 0:k="";break;default:k=this.tail.substring(0,f),this.tail=this.tail.substring(f)}this.pos+=k.length;return k};A.prototype.push=function(f){return new A(f,this)};A.prototype.lookup=function(f){var k=this.cache;if(k.hasOwnProperty(f))var l=k[f];else{for(var p=this,w,z,x=!1;p;){if(0<f.indexOf("."))for(l=p.view,w=f.split("."),z=0;null!=l&&z<w.length;){if(!h(l,w[z])){l=null;break}z===w.length-1&&(x=!0);l=l[w[z++]]}else h(p.view,f)?(l=p.view[f],x=!0):l=null;if(x)break;p=p.parent}k[f]=
l}b(l)&&(l=l.call(this.view));return l};q.prototype.clearCache=function(){this.cache={}};q.prototype.parse=function(f,k){var l=this.cache,p=l[f];null==p&&(p=l[f]=u(f,k));return p};q.prototype.render=function(f,k,l){var p=this.parse(f);k=k instanceof A?k:new A(k);return this.renderTokens(p,k,l,f)};q.prototype.renderTokens=function(f,k,l,p){for(var w="",z,x,t,M=0,Q=f.length;M<Q;++M)t=void 0,z=f[M],x=z[0],"#"===x?t=this.renderSection(z,k,l,p):"^"===x?t=this.renderInverted(z,k,l,p):">"===x?t=this.renderPartial(z,
k,l,p):"&"===x?t=this.unescapedValue(z,k):"name"===x?t=this.escapedValue(z,k):"text"===x&&(t=this.rawValue(z)),void 0!==t&&(w+=t);return w};q.prototype.renderSection=function(f,k,l,p){function w(fa){return z.render(fa,k,l)}var z=this,x="",t=k.lookup(f[1]);if(t){if(P(t))for(var M=0,Q=t.length;M<Q;++M)x+=this.renderTokens(f[4],k.push(t[M]),l,p);else if("object"===typeof t||"string"===typeof t||"number"===typeof t)x+=this.renderTokens(f[4],k.push(t),l,p);else if(b(t)){if("string"!==typeof p)throw Error("Cannot use higher-order sections without the original template");
t=t.call(k.view,p.slice(f[3],f[5]),w);null!=t&&(x+=t)}else x+=this.renderTokens(f[4],k,l,p);return x}};q.prototype.renderInverted=function(f,k,l,p){var w=k.lookup(f[1]);if(!w||P(w)&&0===w.length)return this.renderTokens(f[4],k,l,p)};q.prototype.renderPartial=function(f,k,l){if(l&&(f=b(l)?l(f[1]):l[f[1]],null!=f))return this.renderTokens(this.parse(f),k,l,f)};q.prototype.unescapedValue=function(f,k){f=k.lookup(f[1]);if(null!=f)return a.sanitizeUnescaped?a.sanitizeUnescaped(f):f};q.prototype.escapedValue=
function(f,k){f=k.lookup(f[1]);if(null!=f)return a.escape(f)};q.prototype.rawValue=function(f){return f[1]};a.name="mustache.js";a.version="2.2.0";a.tags=["{{","}}"];var ya=new q;a.clearCache=function(){return ya.clearCache()};a.parse=function(f,k){return ya.parse(f,k)};a.render=function(f,k,l){if("string"!==typeof f)throw new TypeError('Invalid template! Template should be a "string" but "'+c(f)+'" was given as the first argument for mustache#render(template, view, partials)');return ya.render(f,
k,l)};a.to_html=function(f,k,l,p){f=a.render(f,k,l);if(b(p))p(f);else return f};a.escape=function(f){return String(f).replace(/[&<>"'`=\/]/g,function(k){return la[k]})};a.sanitizeUnescaped=null;a.setUnescapedSanitizer=function(f){a.sanitizeUnescaped=f};a.Scanner=E;a.Context=A;a.Writer=q})(gd);function Y(a,b){Ta.call(this,a,b);var c=this;Ga(b,function(){return new Wc(b.document)});this.C=Qa(b,"purifier");gd.setUnescapedSanitizer(function(d){return c.C.purifyTagsForTripleMustache(d)})}Y.prototype=ca(Ta.prototype);Y.prototype.constructor=Y;if(na)na(Y,Ta);else for(var hd in Ta)if("prototype"!=hd)if(Object.defineProperties){var id=Object.getOwnPropertyDescriptor(Ta,hd);id&&Object.defineProperty(Y,hd,id)}else Y[hd]=Ta[hd];Y.M=Ta.prototype;
Y.prototype.compileCallback=function(){if(!this.viewerCanRenderTemplates()){this.G={};if("TEMPLATE"==this.element.tagName){var a=this.element;if("content"in a)var b=a.content.cloneNode(!0);else{b=a.ownerDocument.createDocumentFragment();var c=b.ownerDocument.createDocumentFragment();for(a=a.firstChild;a;a=a.nextSibling)c.appendChild(a.cloneNode(!0));b.appendChild(c)}jd(this,b);c=this.element.ownerDocument.createElement("div");c.appendChild(b);b=c.innerHTML}else b="SCRIPT"==this.element.tagName?this.element.textContent:
"";this.H=b;try{gd.parse(this.H,void 0)}catch(d){Ea().error("amp-mustache",d.message,this.element)}}};function jd(a,b){var c=b.querySelectorAll("template");Sa(c,function(d,h){h="__AMP_NESTED_TEMPLATE_"+h;a.G[h]=d.outerHTML;var r=a.element.ownerDocument.createTextNode("{{{"+h+"}}}");d.parentNode.replaceChild(r,d)})}Y.prototype.setHtml=function(a){var b=this.tryUnwrap(this.C.purifyHtml("<div><div>"+(a+"</div></div>")).firstElementChild);return this.unwrapChildren(b)};
Y.prototype.render=function(a){return this.tryUnwrap(kd(this,a))};Y.prototype.renderAsString=function(a){return kd(this,a).innerHTML};function kd(a,b){var c=b;"object"===typeof b&&(c=Object.assign({},b,a.G));b=gd.render(a.H,c,void 0);return a.C.purifyHtml("<div>"+b+"</div>").firstElementChild}(function(a){a.registerTemplate("amp-mustache",Y)})(self.AMP);
})});

//# sourceMappingURL=amp-mustache-0.2.js.map

/*This file was exported by "Export WP Page to Static HTML" plugin which created by ReCorp (https://myrecorp.com) */